version: 1
disable_existing_loggers: False

formatters:
  default_formatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  default_handler:
    formatter: default_formatter
    class: logging.StreamHandler
    stream: ext://sys.stderr

loggers:
  default_logger:
    level: INFO
    handlers:
      - default_handler
    propagate: no

root:
  level: DEBUG
  handlers:
    - default_handler
  propagate: no